import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ja">
            <body>
                <header>
                    <p>ヘッダー</p>
                </header>
                {children}
                <footer>
                    <p>フッター</p>
                </footer>
            </body>
        </html>
    );
}
